// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpr_ui.proto

package com.digitald4.cpr.ui.proto;

public final class CPRUIProtos {
  private CPRUIProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListSessionsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cpr.ListSessionsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .common.DateRangeType date_range = 1;</code>
     */
    boolean hasDateRange();
    /**
     * <code>optional .common.DateRangeType date_range = 1;</code>
     */
    com.digitald4.common.proto.DD4UIProtos.DateRangeType getDateRange();

    /**
     * <code>optional int64 ref_date = 2;</code>
     */
    boolean hasRefDate();
    /**
     * <code>optional int64 ref_date = 2;</code>
     */
    long getRefDate();

    /**
     * <code>optional int32 tranning_id = 3;</code>
     */
    boolean hasTranningId();
    /**
     * <code>optional int32 tranning_id = 3;</code>
     */
    int getTranningId();
  }
  /**
   * Protobuf type {@code cpr.ListSessionsRequest}
   */
  public  static final class ListSessionsRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cpr.ListSessionsRequest)
      ListSessionsRequestOrBuilder {
    // Use ListSessionsRequest.newBuilder() to construct.
    private ListSessionsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ListSessionsRequest() {
      dateRange_ = 0;
      refDate_ = 0L;
      tranningId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListSessionsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.digitald4.common.proto.DD4UIProtos.DateRangeType value = com.digitald4.common.proto.DD4UIProtos.DateRangeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dateRange_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              refDate_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              tranningId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_ListSessionsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_ListSessionsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest.class, com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest.Builder.class);
    }

    private int bitField0_;
    public static final int DATE_RANGE_FIELD_NUMBER = 1;
    private int dateRange_;
    /**
     * <code>optional .common.DateRangeType date_range = 1;</code>
     */
    public boolean hasDateRange() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .common.DateRangeType date_range = 1;</code>
     */
    public com.digitald4.common.proto.DD4UIProtos.DateRangeType getDateRange() {
      com.digitald4.common.proto.DD4UIProtos.DateRangeType result = com.digitald4.common.proto.DD4UIProtos.DateRangeType.valueOf(dateRange_);
      return result == null ? com.digitald4.common.proto.DD4UIProtos.DateRangeType.UNSPECIFIED : result;
    }

    public static final int REF_DATE_FIELD_NUMBER = 2;
    private long refDate_;
    /**
     * <code>optional int64 ref_date = 2;</code>
     */
    public boolean hasRefDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 ref_date = 2;</code>
     */
    public long getRefDate() {
      return refDate_;
    }

    public static final int TRANNING_ID_FIELD_NUMBER = 3;
    private int tranningId_;
    /**
     * <code>optional int32 tranning_id = 3;</code>
     */
    public boolean hasTranningId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 tranning_id = 3;</code>
     */
    public int getTranningId() {
      return tranningId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dateRange_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, refDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, tranningId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dateRange_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, refDate_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, tranningId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cpr.ListSessionsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cpr.ListSessionsRequest)
        com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_ListSessionsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_ListSessionsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest.class, com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest.Builder.class);
      }

      // Construct using com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dateRange_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        refDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        tranningId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_ListSessionsRequest_descriptor;
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest getDefaultInstanceForType() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest.getDefaultInstance();
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest build() {
        com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest buildPartial() {
        com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest result = new com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dateRange_ = dateRange_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.refDate_ = refDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tranningId_ = tranningId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest) {
          return mergeFrom((com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest other) {
        if (other == com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest.getDefaultInstance()) return this;
        if (other.hasDateRange()) {
          setDateRange(other.getDateRange());
        }
        if (other.hasRefDate()) {
          setRefDate(other.getRefDate());
        }
        if (other.hasTranningId()) {
          setTranningId(other.getTranningId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dateRange_ = 0;
      /**
       * <code>optional .common.DateRangeType date_range = 1;</code>
       */
      public boolean hasDateRange() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .common.DateRangeType date_range = 1;</code>
       */
      public com.digitald4.common.proto.DD4UIProtos.DateRangeType getDateRange() {
        com.digitald4.common.proto.DD4UIProtos.DateRangeType result = com.digitald4.common.proto.DD4UIProtos.DateRangeType.valueOf(dateRange_);
        return result == null ? com.digitald4.common.proto.DD4UIProtos.DateRangeType.UNSPECIFIED : result;
      }
      /**
       * <code>optional .common.DateRangeType date_range = 1;</code>
       */
      public Builder setDateRange(com.digitald4.common.proto.DD4UIProtos.DateRangeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dateRange_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.DateRangeType date_range = 1;</code>
       */
      public Builder clearDateRange() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dateRange_ = 0;
        onChanged();
        return this;
      }

      private long refDate_ ;
      /**
       * <code>optional int64 ref_date = 2;</code>
       */
      public boolean hasRefDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 ref_date = 2;</code>
       */
      public long getRefDate() {
        return refDate_;
      }
      /**
       * <code>optional int64 ref_date = 2;</code>
       */
      public Builder setRefDate(long value) {
        bitField0_ |= 0x00000002;
        refDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 ref_date = 2;</code>
       */
      public Builder clearRefDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        refDate_ = 0L;
        onChanged();
        return this;
      }

      private int tranningId_ ;
      /**
       * <code>optional int32 tranning_id = 3;</code>
       */
      public boolean hasTranningId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 tranning_id = 3;</code>
       */
      public int getTranningId() {
        return tranningId_;
      }
      /**
       * <code>optional int32 tranning_id = 3;</code>
       */
      public Builder setTranningId(int value) {
        bitField0_ |= 0x00000004;
        tranningId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tranning_id = 3;</code>
       */
      public Builder clearTranningId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tranningId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cpr.ListSessionsRequest)
    }

    // @@protoc_insertion_point(class_scope:cpr.ListSessionsRequest)
    private static final com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest();
    }

    public static com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ListSessionsRequest>
        PARSER = new com.google.protobuf.AbstractParser<ListSessionsRequest>() {
      public ListSessionsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ListSessionsRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ListSessionsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListSessionsRequest> getParserForType() {
      return PARSER;
    }

    public com.digitald4.cpr.ui.proto.CPRUIProtos.ListSessionsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrainningUIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cpr.TrainningUI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string description = 3;</code>
     */
    boolean hasDescription();
    /**
     * <code>required string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>required string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code cpr.TrainningUI}
   */
  public  static final class TrainningUI extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cpr.TrainningUI)
      TrainningUIOrBuilder {
    // Use TrainningUI.newBuilder() to construct.
    private TrainningUI(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TrainningUI() {
      id_ = 0;
      name_ = "";
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrainningUI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              description_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningUI_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningUI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI.class, com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>required string description = 3;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cpr.TrainningUI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cpr.TrainningUI)
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningUI_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningUI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI.class, com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI.Builder.class);
      }

      // Construct using com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningUI_descriptor;
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI getDefaultInstanceForType() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI.getDefaultInstance();
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI build() {
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI buildPartial() {
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI result = new com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI) {
          return mergeFrom((com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI other) {
        if (other == com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasDescription()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>required string description = 3;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>required string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cpr.TrainningUI)
    }

    // @@protoc_insertion_point(class_scope:cpr.TrainningUI)
    private static final com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI();
    }

    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TrainningUI>
        PARSER = new com.google.protobuf.AbstractParser<TrainningUI>() {
      public TrainningUI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TrainningUI(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TrainningUI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrainningUI> getParserForType() {
      return PARSER;
    }

    public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningUI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrainningSessionUIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cpr.TrainningSessionUI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 trainning_id = 2;</code>
     */
    boolean hasTrainningId();
    /**
     * <code>optional int32 trainning_id = 2;</code>
     */
    int getTrainningId();

    /**
     * <code>optional int64 start_time_millis = 3;</code>
     */
    boolean hasStartTimeMillis();
    /**
     * <code>optional int64 start_time_millis = 3;</code>
     */
    long getStartTimeMillis();

    /**
     * <code>optional int64 duration_millis = 4;</code>
     */
    boolean hasDurationMillis();
    /**
     * <code>optional int64 duration_millis = 4;</code>
     */
    long getDurationMillis();

    /**
     * <code>optional double cost = 5;</code>
     */
    boolean hasCost();
    /**
     * <code>optional double cost = 5;</code>
     */
    double getCost();

    /**
     * <code>optional .common.GPSAddress location = 6;</code>
     */
    boolean hasLocation();
    /**
     * <code>optional .common.GPSAddress location = 6;</code>
     */
    com.digitald4.common.proto.DD4UIProtos.GPSAddress getLocation();
    /**
     * <code>optional .common.GPSAddress location = 6;</code>
     */
    com.digitald4.common.proto.DD4UIProtos.GPSAddressOrBuilder getLocationOrBuilder();
  }
  /**
   * Protobuf type {@code cpr.TrainningSessionUI}
   */
  public  static final class TrainningSessionUI extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cpr.TrainningSessionUI)
      TrainningSessionUIOrBuilder {
    // Use TrainningSessionUI.newBuilder() to construct.
    private TrainningSessionUI(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TrainningSessionUI() {
      id_ = 0;
      trainningId_ = 0;
      startTimeMillis_ = 0L;
      durationMillis_ = 0L;
      cost_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrainningSessionUI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              trainningId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              startTimeMillis_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              durationMillis_ = input.readInt64();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              cost_ = input.readDouble();
              break;
            }
            case 50: {
              com.digitald4.common.proto.DD4UIProtos.GPSAddress.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(com.digitald4.common.proto.DD4UIProtos.GPSAddress.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningSessionUI_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningSessionUI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI.class, com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TRAINNING_ID_FIELD_NUMBER = 2;
    private int trainningId_;
    /**
     * <code>optional int32 trainning_id = 2;</code>
     */
    public boolean hasTrainningId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 trainning_id = 2;</code>
     */
    public int getTrainningId() {
      return trainningId_;
    }

    public static final int START_TIME_MILLIS_FIELD_NUMBER = 3;
    private long startTimeMillis_;
    /**
     * <code>optional int64 start_time_millis = 3;</code>
     */
    public boolean hasStartTimeMillis() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 start_time_millis = 3;</code>
     */
    public long getStartTimeMillis() {
      return startTimeMillis_;
    }

    public static final int DURATION_MILLIS_FIELD_NUMBER = 4;
    private long durationMillis_;
    /**
     * <code>optional int64 duration_millis = 4;</code>
     */
    public boolean hasDurationMillis() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 duration_millis = 4;</code>
     */
    public long getDurationMillis() {
      return durationMillis_;
    }

    public static final int COST_FIELD_NUMBER = 5;
    private double cost_;
    /**
     * <code>optional double cost = 5;</code>
     */
    public boolean hasCost() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double cost = 5;</code>
     */
    public double getCost() {
      return cost_;
    }

    public static final int LOCATION_FIELD_NUMBER = 6;
    private com.digitald4.common.proto.DD4UIProtos.GPSAddress location_;
    /**
     * <code>optional .common.GPSAddress location = 6;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .common.GPSAddress location = 6;</code>
     */
    public com.digitald4.common.proto.DD4UIProtos.GPSAddress getLocation() {
      return location_ == null ? com.digitald4.common.proto.DD4UIProtos.GPSAddress.getDefaultInstance() : location_;
    }
    /**
     * <code>optional .common.GPSAddress location = 6;</code>
     */
    public com.digitald4.common.proto.DD4UIProtos.GPSAddressOrBuilder getLocationOrBuilder() {
      return location_ == null ? com.digitald4.common.proto.DD4UIProtos.GPSAddress.getDefaultInstance() : location_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, trainningId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, startTimeMillis_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, durationMillis_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, cost_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, getLocation());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, trainningId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, startTimeMillis_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, durationMillis_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, cost_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getLocation());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cpr.TrainningSessionUI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cpr.TrainningSessionUI)
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningSessionUI_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningSessionUI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI.class, com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI.Builder.class);
      }

      // Construct using com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        trainningId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        startTimeMillis_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        durationMillis_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        cost_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.internal_static_cpr_TrainningSessionUI_descriptor;
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI getDefaultInstanceForType() {
        return com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI.getDefaultInstance();
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI build() {
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI buildPartial() {
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI result = new com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.trainningId_ = trainningId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.startTimeMillis_ = startTimeMillis_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.durationMillis_ = durationMillis_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cost_ = cost_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI) {
          return mergeFrom((com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI other) {
        if (other == com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTrainningId()) {
          setTrainningId(other.getTrainningId());
        }
        if (other.hasStartTimeMillis()) {
          setStartTimeMillis(other.getStartTimeMillis());
        }
        if (other.hasDurationMillis()) {
          setDurationMillis(other.getDurationMillis());
        }
        if (other.hasCost()) {
          setCost(other.getCost());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int trainningId_ ;
      /**
       * <code>optional int32 trainning_id = 2;</code>
       */
      public boolean hasTrainningId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 trainning_id = 2;</code>
       */
      public int getTrainningId() {
        return trainningId_;
      }
      /**
       * <code>optional int32 trainning_id = 2;</code>
       */
      public Builder setTrainningId(int value) {
        bitField0_ |= 0x00000002;
        trainningId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 trainning_id = 2;</code>
       */
      public Builder clearTrainningId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trainningId_ = 0;
        onChanged();
        return this;
      }

      private long startTimeMillis_ ;
      /**
       * <code>optional int64 start_time_millis = 3;</code>
       */
      public boolean hasStartTimeMillis() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 start_time_millis = 3;</code>
       */
      public long getStartTimeMillis() {
        return startTimeMillis_;
      }
      /**
       * <code>optional int64 start_time_millis = 3;</code>
       */
      public Builder setStartTimeMillis(long value) {
        bitField0_ |= 0x00000004;
        startTimeMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start_time_millis = 3;</code>
       */
      public Builder clearStartTimeMillis() {
        bitField0_ = (bitField0_ & ~0x00000004);
        startTimeMillis_ = 0L;
        onChanged();
        return this;
      }

      private long durationMillis_ ;
      /**
       * <code>optional int64 duration_millis = 4;</code>
       */
      public boolean hasDurationMillis() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 duration_millis = 4;</code>
       */
      public long getDurationMillis() {
        return durationMillis_;
      }
      /**
       * <code>optional int64 duration_millis = 4;</code>
       */
      public Builder setDurationMillis(long value) {
        bitField0_ |= 0x00000008;
        durationMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 duration_millis = 4;</code>
       */
      public Builder clearDurationMillis() {
        bitField0_ = (bitField0_ & ~0x00000008);
        durationMillis_ = 0L;
        onChanged();
        return this;
      }

      private double cost_ ;
      /**
       * <code>optional double cost = 5;</code>
       */
      public boolean hasCost() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double cost = 5;</code>
       */
      public double getCost() {
        return cost_;
      }
      /**
       * <code>optional double cost = 5;</code>
       */
      public Builder setCost(double value) {
        bitField0_ |= 0x00000010;
        cost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double cost = 5;</code>
       */
      public Builder clearCost() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cost_ = 0D;
        onChanged();
        return this;
      }

      private com.digitald4.common.proto.DD4UIProtos.GPSAddress location_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.digitald4.common.proto.DD4UIProtos.GPSAddress, com.digitald4.common.proto.DD4UIProtos.GPSAddress.Builder, com.digitald4.common.proto.DD4UIProtos.GPSAddressOrBuilder> locationBuilder_;
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public com.digitald4.common.proto.DD4UIProtos.GPSAddress getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? com.digitald4.common.proto.DD4UIProtos.GPSAddress.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public Builder setLocation(com.digitald4.common.proto.DD4UIProtos.GPSAddress value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public Builder setLocation(
          com.digitald4.common.proto.DD4UIProtos.GPSAddress.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public Builder mergeLocation(com.digitald4.common.proto.DD4UIProtos.GPSAddress value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              location_ != null &&
              location_ != com.digitald4.common.proto.DD4UIProtos.GPSAddress.getDefaultInstance()) {
            location_ =
              com.digitald4.common.proto.DD4UIProtos.GPSAddress.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          locationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public com.digitald4.common.proto.DD4UIProtos.GPSAddress.Builder getLocationBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      public com.digitald4.common.proto.DD4UIProtos.GPSAddressOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              com.digitald4.common.proto.DD4UIProtos.GPSAddress.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>optional .common.GPSAddress location = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.digitald4.common.proto.DD4UIProtos.GPSAddress, com.digitald4.common.proto.DD4UIProtos.GPSAddress.Builder, com.digitald4.common.proto.DD4UIProtos.GPSAddressOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.digitald4.common.proto.DD4UIProtos.GPSAddress, com.digitald4.common.proto.DD4UIProtos.GPSAddress.Builder, com.digitald4.common.proto.DD4UIProtos.GPSAddressOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:cpr.TrainningSessionUI)
    }

    // @@protoc_insertion_point(class_scope:cpr.TrainningSessionUI)
    private static final com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI();
    }

    public static com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TrainningSessionUI>
        PARSER = new com.google.protobuf.AbstractParser<TrainningSessionUI>() {
      public TrainningSessionUI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TrainningSessionUI(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TrainningSessionUI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrainningSessionUI> getParserForType() {
      return PARSER;
    }

    public com.digitald4.cpr.ui.proto.CPRUIProtos.TrainningSessionUI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cpr_ListSessionsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cpr_ListSessionsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cpr_TrainningUI_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cpr_TrainningUI_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cpr_TrainningSessionUI_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cpr_TrainningSessionUI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014cpr_ui.proto\022\003cpr\032\017common_ui.proto\"g\n\023" +
      "ListSessionsRequest\022)\n\ndate_range\030\001 \001(\0162" +
      "\025.common.DateRangeType\022\020\n\010ref_date\030\002 \001(\003" +
      "\022\023\n\013tranning_id\030\003 \001(\005\"<\n\013TrainningUI\022\n\n\002" +
      "id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\023\n\013description\030\003 " +
      "\002(\t\"\236\001\n\022TrainningSessionUI\022\n\n\002id\030\001 \001(\005\022\024" +
      "\n\014trainning_id\030\002 \001(\005\022\031\n\021start_time_milli" +
      "s\030\003 \001(\003\022\027\n\017duration_millis\030\004 \001(\003\022\014\n\004cost" +
      "\030\005 \001(\001\022$\n\010location\030\006 \001(\0132\022.common.GPSAdd" +
      "ressB)\n\032com.digitald4.cpr.ui.protoB\013CPRU",
      "IProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.digitald4.common.proto.DD4UIProtos.getDescriptor(),
        }, assigner);
    internal_static_cpr_ListSessionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cpr_ListSessionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cpr_ListSessionsRequest_descriptor,
        new java.lang.String[] { "DateRange", "RefDate", "TranningId", });
    internal_static_cpr_TrainningUI_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cpr_TrainningUI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cpr_TrainningUI_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_cpr_TrainningSessionUI_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cpr_TrainningSessionUI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cpr_TrainningSessionUI_descriptor,
        new java.lang.String[] { "Id", "TrainningId", "StartTimeMillis", "DurationMillis", "Cost", "Location", });
    com.digitald4.common.proto.DD4UIProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
