/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.cpr.GetReservationRequest');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cpr.GetReservationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cpr.GetReservationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.cpr.GetReservationRequest.displayName = 'proto.cpr.GetReservationRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cpr.GetReservationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cpr.GetReservationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cpr.GetReservationRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.cpr.GetReservationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    email: jspb.Message.getField(msg, 1),
    confirmationCode: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.cpr.GetReservationRequest} The clone.
 */
proto.cpr.GetReservationRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.cpr.GetReservationRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * required string email = 1;
 * @return {string}
 */
proto.cpr.GetReservationRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getField(this, 1));
};


/** @param {string|undefined} value  */
proto.cpr.GetReservationRequest.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.cpr.GetReservationRequest.prototype.clearEmail = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * required string confirmation_code = 2;
 * @return {string}
 */
proto.cpr.GetReservationRequest.prototype.getConfirmationCode = function() {
  return /** @type {string} */ (jspb.Message.getField(this, 2));
};


/** @param {string|undefined} value  */
proto.cpr.GetReservationRequest.prototype.setConfirmationCode = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.cpr.GetReservationRequest.prototype.clearConfirmationCode = function() {
  jspb.Message.setField(this, 2, undefined);
};


