/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.cpr.ReservationUI');
goog.provide('proto.cpr.ReservationUI.StudentUI');

goog.require('jspb.Message');

goog.forwardDeclare('proto.cpr.ClassResult');
goog.forwardDeclare('proto.cpr.PaymentStatus');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cpr.ReservationUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cpr.ReservationUI.repeatedFields_, null);
};
goog.inherits(proto.cpr.ReservationUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.cpr.ReservationUI.displayName = 'proto.cpr.ReservationUI';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cpr.ReservationUI.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cpr.ReservationUI.prototype.toObject = function(opt_includeInstance) {
  return proto.cpr.ReservationUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cpr.ReservationUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.cpr.ReservationUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getField(msg, 1),
    sessionId: jspb.Message.getField(msg, 2),
    contactEmail: jspb.Message.getField(msg, 3),
    confirmationCode: jspb.Message.getField(msg, 4),
    paymentStatus: jspb.Message.getField(msg, 5),
    paymentConfirmationCode: jspb.Message.getField(msg, 6),
    studentList: jspb.Message.toObjectList(msg.getStudentList(),
    proto.cpr.ReservationUI.StudentUI.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.cpr.ReservationUI} The clone.
 */
proto.cpr.ReservationUI.prototype.cloneMessage = function() {
  return /** @type {!proto.cpr.ReservationUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number?}
 */
proto.cpr.ReservationUI.prototype.getId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.cpr.ReservationUI.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.cpr.ReservationUI.prototype.clearId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional int32 session_id = 2;
 * @return {number?}
 */
proto.cpr.ReservationUI.prototype.getSessionId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.cpr.ReservationUI.prototype.setSessionId = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.cpr.ReservationUI.prototype.clearSessionId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * optional string contact_email = 3;
 * @return {string?}
 */
proto.cpr.ReservationUI.prototype.getContactEmail = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.cpr.ReservationUI.prototype.setContactEmail = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.cpr.ReservationUI.prototype.clearContactEmail = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * optional string confirmation_code = 4;
 * @return {string?}
 */
proto.cpr.ReservationUI.prototype.getConfirmationCode = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 4));
};


/** @param {string?|undefined} value  */
proto.cpr.ReservationUI.prototype.setConfirmationCode = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.cpr.ReservationUI.prototype.clearConfirmationCode = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * optional PaymentStatus payment_status = 5;
 * @return {proto.cpr.PaymentStatus}
 */
proto.cpr.ReservationUI.prototype.getPaymentStatus = function() {
  return /** @type {proto.cpr.PaymentStatus} */ (jspb.Message.getField(this, 5));
};


/** @param {proto.cpr.PaymentStatus|undefined} value  */
proto.cpr.ReservationUI.prototype.setPaymentStatus = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.cpr.ReservationUI.prototype.clearPaymentStatus = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * optional string payment_confirmation_code = 6;
 * @return {string?}
 */
proto.cpr.ReservationUI.prototype.getPaymentConfirmationCode = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 6));
};


/** @param {string?|undefined} value  */
proto.cpr.ReservationUI.prototype.setPaymentConfirmationCode = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.cpr.ReservationUI.prototype.clearPaymentConfirmationCode = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * repeated StudentUI student = 7;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.cpr.ReservationUI.StudentUI>}
 */
proto.cpr.ReservationUI.prototype.getStudentList = function() {
  return /** @type{!Array.<!proto.cpr.ReservationUI.StudentUI>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cpr.ReservationUI.StudentUI, 7));
};


/** @param {Array.<!proto.cpr.ReservationUI.StudentUI>|undefined} value  */
proto.cpr.ReservationUI.prototype.setStudentList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


proto.cpr.ReservationUI.prototype.clearStudentList = function() {
  this.setStudentList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cpr.ReservationUI.StudentUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cpr.ReservationUI.StudentUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.cpr.ReservationUI.StudentUI.displayName = 'proto.cpr.ReservationUI.StudentUI';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cpr.ReservationUI.StudentUI.prototype.toObject = function(opt_includeInstance) {
  return proto.cpr.ReservationUI.StudentUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cpr.ReservationUI.StudentUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.cpr.ReservationUI.StudentUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getField(msg, 1),
    name: jspb.Message.getField(msg, 2),
    email: jspb.Message.getField(msg, 3),
    result: jspb.Message.getField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.cpr.ReservationUI.StudentUI} The clone.
 */
proto.cpr.ReservationUI.StudentUI.prototype.cloneMessage = function() {
  return /** @type {!proto.cpr.ReservationUI.StudentUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number?}
 */
proto.cpr.ReservationUI.StudentUI.prototype.getId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.cpr.ReservationUI.StudentUI.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.cpr.ReservationUI.StudentUI.prototype.clearId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional string name = 2;
 * @return {string?}
 */
proto.cpr.ReservationUI.StudentUI.prototype.getName = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 2));
};


/** @param {string?|undefined} value  */
proto.cpr.ReservationUI.StudentUI.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.cpr.ReservationUI.StudentUI.prototype.clearName = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * optional string email = 3;
 * @return {string?}
 */
proto.cpr.ReservationUI.StudentUI.prototype.getEmail = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.cpr.ReservationUI.StudentUI.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.cpr.ReservationUI.StudentUI.prototype.clearEmail = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * optional ClassResult result = 4;
 * @return {proto.cpr.ClassResult}
 */
proto.cpr.ReservationUI.StudentUI.prototype.getResult = function() {
  return /** @type {proto.cpr.ClassResult} */ (jspb.Message.getField(this, 4));
};


/** @param {proto.cpr.ClassResult|undefined} value  */
proto.cpr.ReservationUI.StudentUI.prototype.setResult = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.cpr.ReservationUI.StudentUI.prototype.clearResult = function() {
  jspb.Message.setField(this, 4, undefined);
};


