CREATE DATABASE /*!32312 IF NOT EXISTS*/ `cpr` /*!40100 DEFAULT CHARACTER SET latin1 */;  

USE `cpr`;

CREATE TABLE GeneralData(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	GROUP_ID INT,
	IN_GROUP_ID INT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	RANK DOUBLE,
	ACTIVE BOOLEAN DEFAULT 1,
	DESCRIPTION VARCHAR(256),
	DATA VARCHAR(128)
);
CREATE INDEX GeneralData_GroupId ON GeneralData (GROUP_ID);

CREATE TABLE User(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TYPE_ID INT NOT NULL,
	EMAIL VARCHAR(64) NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	DISABLED BOOLEAN,
	READ_ONLY BOOLEAN,
	PASSWORD VARCHAR(128),
	NOTES VARCHAR(256),
	LAST_LOGIN DATETIME
);

CREATE TABLE Trainning(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(128),
  DESCRIPTION VARCHAR(512),
  DURATION_MILLIS DATE,
  COST DOUBLE,
	ADDRESS VARCHAR(128),
	UNIT VARCHAR(32),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE
);

CREATE TABLE TrainningSession(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TRAINNING_ID INT,
  START_TIME_MILLIS DATE,
  DURATION_MILLIS INT,
  COST DOUBLE,
	ADDRESS VARCHAR(128),
	UNIT VARCHAR(32),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE
);
CREATE INDEX TrainningSession_TrainningId ON TrainningSession (TRAINNING_ID);

CREATE TABLE Reservation(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SESSION_ID INT,
	CONTACT_EMAIL VARCHAR(128),
	PAYMENT_STATUS INT,
	PAYMENT_CONFIRMATION_CODE VARCHAR(128)
);
CREATE INDEX Reservation_SessionId ON Reservation (SESSION_ID);

CREATE TABLE Student(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	RESERVATION_ID INT,
	NAME VARCHAR(64),
	EMAIL VARCHAR(64),
	RESULT INT
);
CREATE INDEX Student_ReservationId ON Student (RESERVATION_ID);

GRANT INSERT, SELECT, UPDATE, DELETE ON cpr.* TO 'dd4_user'@'localhost';
